# User provided contents:
#   - submission tls certs
#   - DKIM keys and policies
#   - virtual alias domains
#   - virtual alias maps
#   - transports
#   - SRS domain
version: '2'

services:
  postfix:
    image: lisnaz/opendkim:latest
    ports:
    - "9901:9901/tcp"
    volumes:
    - opendkim:/srv/opendkim
    environment:
      DKIM_DOMAIN: example.com
      DKIM_TRUSTED_HOSTS: |
        127.0.0.1
        ::1
        localhost
        google.com

volumes:
  opendkim:
